version: "3.8"

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my-db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    
    adminer:
        image: adminer
        container_name: adminer
        depends_on:
            - mysql
        environment:
            ADMINER_DEFAULT_DB: my-db
        ports:
            - "8080:8080"

volumes:
    mysql-data: {}
